language: php
dist: trusty

matrix:
  include:
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
      addons:
        sauce_connect: true
        hosts:
          - cops-travis
    - php: "7.0"
    - php: "hhvm"
  allow_failures:
    - php: "hhvm"
    - php: "5.5"
    - php: "5.4"

before_script:
  - composer selfupdate
  - composer global require "fxp/composer-asset-plugin:~1.1"
  - 'if [ "${TRAVIS_PHP_VERSION}" = "5.5" ] || [ "${TRAVIS_PHP_VERSION}" = "5.4" ]; then rm composer.lock && sed -i "/platform/d" composer.json ; fi'
  - composer install
  - npm install -g jshint
  - jshint --version
script:
  - vendor/bin/phpunit
  - jshint --verbose --show-non-errors util.js
  - php test/coverage-checker.php clover.xml 45
after_success:
  - chmod +x test/prepareSauceTest.sh
  - test/prepareSauceTest.sh
env:
  global:
  - SAUCE_USERNAME=seblucas
  - secure: VVxocvmz6WYr3tZSTA42M/LUhaHoBWw5onh85hnquoMaxspd3tDCyfQIowTTmEXikRh2T0CkTH7X3dhVwRTd/Ha9isja1qDo9Lc2flGCoWICF7WFZuom084+d+O+EWx4WZMAw4Lz4w6a5xflpPKnzNs9B0+de0BdTlQ5qSXVrcA=

sudo: false

before_deploy:
  - composer install --no-dev --optimize-autoloader
  - wget http://www.phing.info/get/phing-latest.phar
  - php phing-latest.phar
  - export RELEASE_FILE=$(ls ./cops-*.zip)

deploy:
  provider: releases
  api_key:
    secure: nUQ6uX4+x3VtyrtKjHANl3zLyc0Q9qe2O10ufOFBgcQwWETrE6Gk+Rwn/Kz6OJkg0AGfioptvjh8c28ELV98M+KmhiwhT1VQgs3pa6x9CbggA8fdbGUCq+SC8lnU7MBYIO5gZ36F3RfPwXxXkd09bajiVLbI024IqFSIAONzLXw=
  skip_cleanup: true
  file:
    - "${RELEASE_FILE}"
  on:
    tags: true
    repo: seblucas/cops
    php: 5.6

cache:
  directories:
    - $HOME/.composer/cache
